---
version: '3.7'

services:

  kubectl-awscli:
    build:
      context: .
      target: builder
      args:
        - KUBE_VERSION=1.25.8
        - AWSCLI_VERSION=v3.9.0
    platform: linux/amd64
    entrypoint: bash
    image: ikerry/kubectl-awscli:${APP_TAG:-latest}
