---
version: '3.7'

x-base: &base
  platform: linux/amd64
  build:
    context: .
    target: release

services:

  sh:
    <<: *base
    entrypoint: bash

  kubectl-awscli:
    <<: *base
    image: ikerry/kubectl-awscli:${APP_TAG:-latest}
    entrypoint: bash
