---
version: '3.7'

services:

  tf-toolkit:
    build:
      context: .
      target: release
      args:
        - TERRAFORM_VERSION=0.13.7
        - GOMPLATE_VERSION=v3.9.0
        - YQ_VERSION=v4.9.8
    platform: linux/amd64
    entrypoint: bash
    image: ikerry/tf-toolkit:${APP_TAG:-latest}
