---
version: '3.9'

services:

  sh:
    platform: linux/amd64
    build:
      context: .
      target: builder
      args:
        - TARGETARCH=amd64
        - KUBE_VERSION=1.28.2
        - KUSTOMIZE_VERSION=5.1.0
        - GOMPLATE_VERSION=v3.11.5
        - YQ_VERSION=v4.9.8
        - ISTIO_VERSION=1.18.5
        - HELM_VERSION=v3.12.0
        - CILIUM_CLI_VERSION=v0.15.11
    entrypoint: bash

  k8s-toolkit:
    platform: linux/amd64
    image: ikerry/k8s-toolkit:${APP_TAG:-latest}
    build:
      context: .
      target: release
      args:
        - TARGETARCH=amd64
        - KUBE_VERSION=1.28.2
        - KUSTOMIZE_VERSION=5.1.0
        - GOMPLATE_VERSION=v3.11.5
        - YQ_VERSION=v4.9.8
        - ISTIO_VERSION=1.18.5
        - HELM_VERSION=v3.12.0
        - CILIUM_CLI_VERSION=v0.15.11
    entrypoint: bash
    
