---
version: '3.9'

services:

  k8s-toolkit:
    build:
      context: .
      target: release
      args:
        - TARGETARCH=amd64
        - KUBE_VERSION=1.27.3
        - KUSTOMIZE_VERSION=5.1.0
        - GOMPLATE_VERSION=v3.9.0
        - YQ_VERSION=v4.9.8
        - ISTIO_VERSION=1.18.2
        - HELM_VERSION=v3.12.0
    platform: linux/amd64
    entrypoint: bash
    image: ikerry/k8s-toolkit:${APP_TAG:-latest}
