---
version: '3.7'

services:

  k8s-toolkit:
    build:
      context: .
      target: release
      args:
        - KUBE_VERSION=1.22.1
        - GOMPLATE_VERSION=v3.9.0
        - YQ_VERSION=v4.9.8
    entrypoint: bash
    image: ikerry/k8s-toolkit:${APP_TAG:-latest}
