---
version: '3.7'

services:

  k8s-toolkit:
    build:
      context: .
      target: release
      args:
        - TARGETARCH=amd64
        - KUBE_VERSION=1.26.5
        - GOMPLATE_VERSION=v3.9.0
        - YQ_VERSION=v4.9.8
        - ISTIO_VERSION=1.16.5
    platform: linux/amd64
    entrypoint: bash
    image: ikerry/k8s-toolkit:${APP_TAG:-latest}
