---
version: '3.9'

x-base: &base
  platform: linux/amd64
  build:
    context: .
    target: release

services:

  sh:
    <<: *base
    entrypoint: bash

  k8s-toolkit:
    <<: *base
    image: ikerry/k8s-toolkit:${APP_TAG:-latest}
    entrypoint: bash
    
